swagger: '2.0'
info:
    title: xREventi APIs
    description: This is the API Documentation
    version: 1.0

    servers:
        -url: https://typer-api.onrender.com/api
        description: Deployed API Endpoint

schemes: [http, https]

paths:
    # Signup
    /api/auth/typer/signup:
        post:
            tags:
                - Authentication
            summary: Registration
            produces:
                - application/json
            consumes:
                - application/json
            parameters:
                - in: body
                  name: user
                  schema:
                      type: object
                      properties:
                          name:
                              type: string
                              default: ''
                          email:
                              type: string
                              default: ''
                          password:
                              type: string
                              default: ''
            responses:
                201:
                    description: Success, new user created successfully
                400:
                    description: Unable to register, error

    # Create Event
    /api/event/:
        post:
            tags:
                - Event
            summary: Create Event
            produces:
                - application/json
            consumes:
                - application/json
            parameters:
                - in: body
                  name: event
                  schema:
                      type: object
                      properties:
                          name:
                              type: string
                              default: ''
                          description:
                              type: string
                              default: ''
                          date:
                              type: string
                              default: ''
                          isSelection:
                              type: boolean
                              default: false
                          isPayment:
                              type: boolean
                              default: false
                          amount:
                              type: string
                              default: ''
                          approval:
                              type: array
                              items:
                                  type: object
                                  properties:
                                      id:
                                          type: string
                                          default: ''
                                      name:
                                          type: string
                                          default: ''
            responses:
                201:
                    description: Success, new user created successfully
                400:
                    description: Unable to register, error
